
pathOfSave: d:\All_for\Graphiks\

server:
  port: 80

spring.datasource.url: jdbc:mysql://localhost:3306/ticks
spring.datasource.username: root
#spring.datasource.password: _1Q2w3e4r_
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false